from .base_page import BasePage
from .document_extractor import DocumentExtractorPort
from .http_client import HttpClient
from .document_acquisition import DocumentAcquisitionPort
from .document_persistance import DocumentPersistancePort
from .image_processor import ImageProcessorPort
from .captcha_gateway import SeleniumCaptchaGatewayPort
from .pages import *
from .captcha_solver import CaptchaSolverPort
from .document_downloader import DocumentDownloaderPort
from .municipio_getter import MunicipioGetterPort